
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LTE = 8;
  public static final int CHAR = 22;
  public static final int LPAREN = 17;
  public static final int INT = 21;
  public static final int MINUS = 13;
  public static final int RPAREN = 18;
  public static final int BOOLEAN_LITERAL = 36;
  public static final int CHARACTER_LITERAL = 35;
  public static final int NOT = 4;
  public static final int SEMICOLON = 30;
  public static final int AND = 2;
  public static final int LT = 7;
  public static final int OR = 3;
  public static final int BOOL = 23;
  public static final int COMMA = 31;
  public static final int PLUS = 12;
  public static final int MAIN = 32;
  public static final int IF = 24;
  public static final int EOF = 0;
  public static final int RETURN = 33;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int EQEQ = 6;
  public static final int EQ = 11;
  public static final int GTE = 10;
  public static final int LBRACK = 15;
  public static final int LBRACE = 19;
  public static final int ELSE = 25;
  public static final int RBRACK = 16;
  public static final int WHILE = 26;
  public static final int RBRACE = 20;
  public static final int MULTI = 14;
  public static final int GT = 9;
  public static final int PRINT = 29;
  public static final int NOTEQ = 5;
  public static final int IDENTIFIER = 37;
  public static final int FREE = 28;
  public static final int INTEGER_LITERAL = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "NOTEQ",
  "EQEQ",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "EQ",
  "PLUS",
  "MINUS",
  "MULTI",
  "LBRACK",
  "RBRACK",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "INT",
  "CHAR",
  "BOOL",
  "IF",
  "ELSE",
  "WHILE",
  "NEW",
  "FREE",
  "PRINT",
  "SEMICOLON",
  "COMMA",
  "MAIN",
  "RETURN",
  "INTEGER_LITERAL",
  "CHARACTER_LITERAL",
  "BOOLEAN_LITERAL",
  "IDENTIFIER"
  };
}

